CREATE TABLE client(
	id INT AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(255) NOT NULL ,
	lastname VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);
